---
driver: 
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: cron
    run_list:
      - recipe[opsline-chef-client::cron]
    attributes:
  - name: disable
    run_list:
      - recipe[opsline-chef-client::cron]
      - recipe[opsline-chef-client::disable_chef]
    attributes:
  - name: unregister
    run_list:
      - recipe[opsline-chef-client::unregister_on_shutdown]
    attributes: